### ISSUE TITLE
Question about your Drone and danger integration

### ISSUE THREAD

**Issue by scottyab** [baracaio/comparativo-laravel#76]
Hi @baracaio, sorry this isn't directly related to your project it's a question about your Drone and Danger integration. There's limited examples on the interest and only found yours via an adv Gtihub search. I didn't see that Danger was posting to your PRs on this project so wondering if you got it working? 

I have a similar configuration to you but am unable to get Drone to run my "run Danger PR validator" step when there's a pull request or pull request is updated. Appreciate any insight you might have. Thanks

  ```
name: run Danger PR validator
    pull: if-not-exists
    image: dangersystems/danger-rb
    depends_on:
      - test
    commands:
      - printenv
      - bundle exec danger --fail-on-errors=true --new-comment --remove-previous-comments
    when:
      event:
        include:
          - pull_request
    environment:
      DANGER_GITHUB_API_TOKEN:
        from_secret: DANGER_GITHUB_API_TOKEN
```

Pipeline triggers 

```
trigger:
  event:
    - push
    - pull_request
```
